### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [exfly/cslab#11]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by exfly** [comment]
@unknwon Thank you for your issue. This project is mainly to organize your own test environment, such as how mongo's replicas are configured. I has recently refactored the project and removed some dependencies, `github.com/unknwon/com` is removed. Anyway, thank you very much.
